config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: {
    invitations: 'devise/invitations',
    registrations: 'users/registrations'
  }


  # --------------------------------- STUDENT ----------------------------------
  get 'student_view', to: 'student#student_view'
  get 'student_view_exam_questions', to: 'student#student_view_exam_questions'
  get 'student_exams', to: 'student#student_exams'
  post 'student/submit_student_exam/:id', to: 'student#submit_student_exam', as: 'submit_student_exam'

  #----------------------------------- EXAMS Questions----------------------------------------
  resources :exams do
    resources :questions
  end

  resources :questions, only: %i[edit update]

  resources :questions do
    resources :answers, only: %i[new create show]
  end

  #------------------------------- Teacher ---------------------------------------
  resources :teachers, only: [:index] do
    collection do
      get 'review_scores', to: 'teacher#review_scores', as: :review_scores
      get 'review_exam', to: 'teacher#review_exam', as: :review_exam
    end
    member do
      get 'approval_request/:id', to: 'teacher#approval_request', as: :approval_request
    end
  end

  #--------------------------------- Admin ----------------------------------------
  namespace :admin do
    resources :invitations, only: %i[new create], path: '' do
      collection do
        get :new_invitation
        post :create_invitation
      end
    end
  end

  resources :admin, only: [] do
    collection do
      get 'admin_view', to: 'admin#admin_view'
      get 'review_scores', to: 'admin#review_scores'
      get 'admin_question/:id', to: 'admin#admin_question', as: :admin_question
      post 'approve/:id', to: 'admin#approve', as: :approve_exam
      put 'cancel/:id', to: 'admin#cancel', as: :admin_cancel_exam
    end
  end

  #----------------------------------- USER ---------------------------------------
  devise_scope :user do
    root 'devise/sessions#new'
    get 'devise/invitations/new', to: 'devise/invitations#new', as: :send_user_invitation
    get 'users/sign_out', to: 'devise/sessions#destroy'
  end

  #-------------------------------------------------------------------------------------
  resources :results


  get '/admin', to: 'admin#index', as: :admin_index_path
  get '/teacher', to: 'teacher#index', as: :teacher_index_path
  get '/student', to: 'student#index', as: :student_index_path
end

app/controllers/student_controller.rb
class StudentController < ApplicationController
  before_action :set_student


def student_view
    @exams = Exam.where(status: 1, approved: true) #only approved 
end
def student_view_exam_questions
  subject = params[:subject]
  @exam = Exam.find_by(subject: subject)
  if @exam
    @questions = @exam.questions
  else
    flash[:alert] = "No exam found for the selected subject."
    redirect_to student_view_exams_path # Redirect to the previous page or another appropriate location
  end
end
def submit_student_exam
  @exam = Exam.find(params[:id])
  total = 0
  student_answers = {} # Create a hash to store student answers for each question

  @exam.questions.each do |question|
    user_answer = params.dig(:exam, :questions, question.id.to_s, :text_ans)

    if user_answer.present?
      if user_answer == question.correct_option
        total += question.score
      end

      student_answers[question.id] = user_answer
    end
  end

  current_user.total_score = total
  current_user.update(total_score: total)

  current_user.exams.where(id: @exam.id).update(exam_taken: true)

  @result = Result.create(user: current_user, exam: @exam, total_score: total, text_ans: student_answers)

  redirect_to student_view_path
end

def student_exams
  @user = current_user
  @results = @user.results.includes(:exam)
end


private

def set_student
    @student = current_user # Assuming you have a current_user method
  end

end

app/helpers/student_helper.rb
# frozen_string_literal: true

module StudentHelper
end

app/views/student/index.html.erb
 
<body>
<nav class="navbar navbar-default">
  <div class="container">
    <div class="navbar-header">
      <a class="navbar-brand" href="#">Student Portal</a>
    </div>
    <ul class="nav navbar-nav">
      <% if current_user %>
      <li>
        <%= image_tag current_user.image, style:'height:50px; border-radius:50px;' %>
      </li>
      <li>
        <%= link_to current_user.full_name, edit_user_registration_path, class: 'text-primary' %>
      </li>
      <% end %>
    </ul>
    <ul class="nav navbar-nav navbar-right">
      <li><%= link_to 'Sign Out', destroy_user_session_path, method: :delete %></li>
    </ul>
  </div>
</nav>


  <div class="container">
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= link_to 'Show All Exams', student_view_path(@exams), class: 'btn btn-primary' %>
    <%= link_to 'View My Exams', student_exams_path, class: 'btn btn-primary' %>

    <%= yield %>
  </div>
</body>
</html>

app/views/student/student_exams.html.erb
<div class="container">
  <h1 class="text-center mt-4 bg-primary ">My Exams and Total Scores</h1>

  <% if @results %>
    <table class="table table-striped table-bordered">
      <thead>
        <tr>
          <th>Exam</th>
          <th>Total Score</th>
        </tr>
      </thead>
      <tbody>
        <% @results.each do |result| %>
          <tr>
            <td><%= result.exam.subject %></td>
            <td><%= result.total_score %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  <% else %>
    <p>No exams and scores available.</p>
  <% end %>
 <%= link_to 'Back', student_index_path_path, class: 'btn btn-success' %>
</div>

app/views/student/student_view.html.erb
<!-- app/views/exams/student_view.html.erb -->

<div class="container">
  <h1>Exams Available for Students</h1>
  <% if @exams %>
    <ul>
      <% @exams.each do |exam| %>
        <li>
          <strong>Subject:</strong> <%= exam.subject %><br>
          <% if current_user.has_taken_exam?(exam) %>
          <p>You have already taken this exam. You cannot retake it.</p>
           <% else %>
        <%= link_to 'Take Exam', student_view_exam_questions_path(subject: exam.subject), class: 'btn btn-success' %>
         <% end %>
        </li>
      <% end %>
    </ul>
  <% else %>
    <p>No exams are currently available for students.</p>
  <% end %>
   <h2> <%= link_to 'Back', student_index_path_path, class: 'btn btn-success' %></h2>
</div>

app/views/student/student_view_exam_questions.html.erb
<div class="card-footer bg-light">
  <h1 class='question_head text-center'>Questions</h1>
  <hr><hr>
  <div id="timer" class="text-center">Timer: <span id="timer-countdown"></span></div>
  <%= form_with(model: @exam, url: submit_student_exam_path(@exam), method: :post, html: { class: 'form-group' }) do |f| %>
    <div id="question-container">
      <h3 class=text-center> Total Questions <%= @exam.questions.count %> </h3>
      <hr>
      <% @exam.questions.each_with_index do |question, index| %>
        <% if question.persisted? %>
          <div class='qs-item' id="question-<%= index %>" <%= "style='display: none;'" unless index == 0 %>>
            <p><strong>Description: </strong><%= question.content %></p>
            <% if question.question_type == 'mcq' %>
              <ul>
                <% question.choices.each_with_index do |choice, choice_index| %>
                  <li><strong>Option <%= (choice_index + 1).chr %>:</strong> <%= choice %></li>
                <% end %>
              </ul>
            <% end %>

            <div class="form-group">
             
              <%= f.text_field("questions[#{question.id}][text_ans]", class: 'form-control', placeholder: 'Enter your answer here', data: { question_index: index }) %>
            </div>
            <button id="next-button" class="btn btn-primary">Next Question</button>
            <hr>
          </div>
        <% end %>
      <% end %>
    </div>
    <div class="form-group">
      <%= f.submit 'Submit Answers', class: 'btn btn-primary', id: 'submit-answers-button' %>
    </div>
  <% end %>
</div>