config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: {
    invitations: 'devise/invitations',
    registrations: 'users/registrations'
  }


  # --------------------------------- STUDENT ----------------------------------
  get 'student_view', to: 'student#student_view'
  get 'student_view_exam_questions', to: 'student#student_view_exam_questions'
  get 'student_exams', to: 'student#student_exams'
  post 'student/submit_student_exam/:id', to: 'student#submit_student_exam', as: 'submit_student_exam'

  #----------------------------------- EXAMS Questions----------------------------------------
  resources :exams do
    resources :questions
  end

  resources :questions, only: %i[edit update]

  resources :questions do
    resources :answers, only: %i[new create show]
  end

  #------------------------------- Teacher ---------------------------------------
  resources :teachers, only: [:index] do
    collection do
      get 'review_scores', to: 'teacher#review_scores', as: :review_scores
      get 'review_exam', to: 'teacher#review_exam', as: :review_exam
    end
    member do
      get 'approval_request/:id', to: 'teacher#approval_request', as: :approval_request
    end
  end

  #--------------------------------- Admin ----------------------------------------
  namespace :admin do
    resources :invitations, only: %i[new create], path: '' do
      collection do
        get :new_invitation
        post :create_invitation
      end
    end
  end

  resources :admin, only: [] do
    collection do
      get 'admin_view', to: 'admin#admin_view'
      get 'review_scores', to: 'admin#review_scores'
      get 'admin_question/:id', to: 'admin#admin_question', as: :admin_question
      post 'approve/:id', to: 'admin#approve', as: :approve_exam
      put 'cancel/:id', to: 'admin#cancel', as: :admin_cancel_exam
    end
  end

  #----------------------------------- USER ---------------------------------------
  devise_scope :user do
    root 'devise/sessions#new'
    get 'devise/invitations/new', to: 'devise/invitations#new', as: :send_user_invitation
    get 'users/sign_out', to: 'devise/sessions#destroy'
  end

  #-------------------------------------------------------------------------------------
  resources :results


  get '/admin', to: 'admin#index', as: :admin_index_path
  get '/teacher', to: 'teacher#index', as: :teacher_index_path
  get '/student', to: 'student#index', as: :student_index_path
end

app/controllers/teacher_controller.rb
# frozen_string_literal: true

# Teacher controller
class TeacherController < ApplicationController
 before_action :authenticate_user!
 before_action :check_teacher_role


  def index
    @exam = Exam.order(created_at: :desc).first
  end
  
def review_scores
  @results = Result.with_associations.all
end

  def review_scores
    @results = Result.with_associations.all
  end

  def review_exam
    # Retrieve the list of students
    @students = User.where(role: 'student')
    @exam_results = Result.where(user: @students).includes(:exam)
  end

  def approval_request
    @exam = Exam.find(params[:id])
    @exam.update(status: 'sent') # status 2 indicates that req is sent
    current_user.update(request_sent: false)
    redirect_to exams_path
  end


  private

  def check_teacher_role
    return if current_user.teacher?

    redirect_to root_path, alert: 'You are not authorized to access this page.'
  end
end

app/helpers/teacher_helper.rb
# frozen_string_literal: true

module TeacherHelper
end

app/views/teacher/index.html.erb
<body>
<nav class="navbar navbar-default">
  <div class="container">
    <div class="navbar-header">
      <a class="navbar-brand" href="#">Teacher Portal</a>
    </div>
    <ul class="nav navbar-nav">
      <% if current_user %>
      <li>
        <%= image_tag current_user.image, style:'height:50px; border-radius:50px;' %>
      </li>
      <li>
        <%= link_to current_user.full_name, edit_user_registration_path, class: 'text-primary' %>
      </li>
      <% end %>
    </ul>
    <ul class="nav navbar-nav navbar-right">
      <li><%= link_to 'Sign Out', destroy_user_session_path, method: :delete %></li>
    </ul>
  </div>
</nav>



  <div class="container">
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <a class="btn btn-primary " href="<%= exams_path %>">Create Exam</a>
    <% if @exam %>
     <%= link_to 'Review Exam Scores', review_scores_teachers_path, class: 'btn btn-primary' %>
     <%= link_to 'Review Exam of Students', review_exam_teachers_path, class: 'btn btn-primary' %>
    <% else %>
       <p>No exam found.</p>
    <% end %> 
    <%= yield %>
     
  </div>

</body>
</html>

app/views/teacher/review_exam.html.erb
<h1 class="text-center bg-success">Review Exam of Students</h1>

<% @students.each do |student| %>
  <h2 class="text-center bg-primary"><%= student.full_name %></h2>

  <% @exam_results.where(user: student).group_by { |result| result.exam }.each do |exam, results| %>
    <h3>Exam: <%= exam.subject %></h3>
    <p>Total Score: <%= results.first.total_score %></p>

    <table class="table table-bordered">
      <thead>
        <tr>
          <th>Question</th>
          <th>Correct Option</th>
          <th>User Answer</th>
        </tr>
      </thead>
      <tbody>
        <% results.each do |result| %>
          <% result.exam.questions.each do |question| %>
            <tr>
              <td><%= question.content %></td>
              <td><%= question.correct_option %></td>
              <td>
               <% if result.text_ans.present? %>
               <% answer_hash = eval(result.text_ans) rescue nil %>
               <%= answer_hash[question.id] %>
               <% else %>
              No answer provided
              <% end %>
              </td>
            </tr>
          <% end %>
        <% end %>
      </tbody>
    </table>
  <% end %>
<% end %>

app/views/teacher/review_scores.html.erb
<h1 class='text-center bg-primary'>Review Exam Scores</h1>

<% if @results.any? %>
  <table class="table table-striped table-bordered">
    <thead>
      <tr>
        <th>Student</th>
        <th>Exam</th>
        <th>Score</th>
      </tr>
    </thead>
    <tbody>
      <% @results.each do |result| %>
        <tr>
          <td><%= result.user.full_name %></td>
          <td><%= result.exam.subject %></td>
          <td><%= result.total_score %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <p>No exam scores available.</p>
<% end %>