config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: {
    invitations: 'devise/invitations',
    registrations: 'users/registrations'
  }


  # --------------------------------- STUDENT ----------------------------------
  get 'student_view', to: 'student#student_view'
  get 'student_view_exam_questions', to: 'student#student_view_exam_questions'
  get 'student_exams', to: 'student#student_exams'
  post 'student/submit_student_exam/:id', to: 'student#submit_student_exam', as: 'submit_student_exam'

  #----------------------------------- EXAMS Questions----------------------------------------
  resources :exams do
    resources :questions
  end

  resources :questions, only: %i[edit update]

  resources :questions do
    resources :answers, only: %i[new create show]
  end

  #------------------------------- Teacher ---------------------------------------
  resources :teachers, only: [:index] do
    collection do
      get 'review_scores', to: 'teacher#review_scores', as: :review_scores
      get 'review_exam', to: 'teacher#review_exam', as: :review_exam
    end
    member do
      get 'approval_request/:id', to: 'teacher#approval_request', as: :approval_request
    end
  end

  #--------------------------------- Admin ----------------------------------------
  namespace :admin do
    resources :invitations, only: %i[new create], path: '' do
      collection do
        get :new_invitation
        post :create_invitation
      end
    end
  end

  resources :admin, only: [] do
    collection do
      get 'admin_view', to: 'admin#admin_view'
      get 'review_scores', to: 'admin#review_scores'
      get 'admin_question/:id', to: 'admin#admin_question', as: :admin_question
      post 'approve/:id', to: 'admin#approve', as: :approve_exam
      put 'cancel/:id', to: 'admin#cancel', as: :admin_cancel_exam
    end
  end

  #----------------------------------- USER ---------------------------------------
  devise_scope :user do
    root 'devise/sessions#new'
    get 'devise/invitations/new', to: 'devise/invitations#new', as: :send_user_invitation
    get 'users/sign_out', to: 'devise/sessions#destroy'
  end

  #-------------------------------------------------------------------------------------
  resources :results


  get '/admin', to: 'admin#index', as: :admin_index_path
  get '/teacher', to: 'teacher#index', as: :teacher_index_path
  get '/student', to: 'student#index', as: :student_index_path
end

app/views/admin/admin_question.html.erb
<div class="row mt-5">
    <div class="col-md-12">
      <h1 class="text-center">Exams for Approval</h1>
      <ul class="list-group mt-4">
          <li class="list-group-item d-flex justify-content-between align-items-center">
              <span><%= @exam.subject %></span>
              <%= button_to 'Approve', approve_exam_admin_index_path(@exam), class: 'btn btn-success btn-sm' %>
              <%= button_to 'Cancel Exam', admin_cancel_exam_admin_index_path(@exam), method: :put, data: { confirm: 'Are you sure you want to cancel this exam?' }, class: 'btn btn-danger btn-sm' %>
          </li>

            <!-- Exam Questions -->
          <div class="card-footer bg-light">
            <h1 class="question_head text-center">Questions</h1>
              <% @exam.questions.each do |question| %>
                <% if question.persisted? %>
                  <div class="qs-item">
                    <p><strong>Question:</strong> <%= question.content %></p>
                    <% if question.question_type=='mcq' %>
                    <p><strong>Options </strong><%= question.choices %></p>
                    <%end%>
                    <p><strong>Correct Option:</strong> <%= question.correct_option %></p>
                     <p><strong>Score:</strong> <%= question.score %></p>
                  <hr>
                <% end %>
              <% end %>
          </div>
      </ul>
    </div>
</div>

app/views/admin/admin_question_view.html.erb
<div class="row mt-5">
    <div class="col-md-12">
      <h1 class="text-center">Exams for Approval</h1>
      <ul class="list-group mt-4">
          <li class="list-group-item d-flex justify-content-between align-items-center">
              <span><%= @exam.subject %></span>
              <%= button_to 'Approve', approve_exam_admin_index_path(@exam), class: 'btn btn-success btn-sm' %>
              <%= button_to 'Cancel Exam', admin_cancel_exam_admin_index_path(@exam), method: :put, data: { confirm: 'Are you sure you want to cancel this exam?' }, class: 'btn btn-danger btn-sm' %>
          </li>

            <!-- Exam Questions -->
          <div class="card-footer bg-light">
            <h1 class="question_head text-center">Questions</h1>
              <% @exam.questions.each do |question| %>
                <% if question.persisted? %>
                  <div class="qs-item">
                    <p><strong>Question:</strong> <%= question.content %></p>
                    <% if question.question_type=='mcq' %>
                    <p><strong>Options </strong><%= question.choices %></p>
                    <%end%>
                    <p><strong>Correct Option:</strong> <%= question.correct_option %></p>
                     <p><strong>Score:</strong> <%= question.score %></p>
                  <hr>
                <% end %>
              <% end %>
          </div>
      </ul>
    </div>
</div>

app/views/admin/admin_view.html.erb
<div class="container">
  <div class="row mt-5">
    <div class="col-md-12">
      <h1 class="text-center">List of Exams Created by Teachers</h1>
    <% if @exams_to_approve.any? %>
  <ul class="list-group mt-4">
    <% @exams_to_approve.each do |exam| %>
      <li class="list-group-item">
        <strong>Subject:</strong>
        <%= link_to exam.subject, admin_question_admin_index_path(exam) %>
      </li>
    <% end %>
  </ul>
<% else %>
  <p class="mt-4">No exams approve request by teachers are available.</p>
<% end %>
    </div>
  </div>

  

app/views/admin/approve.html.erb
<div class="container">
  <h1 class="text-center mb-4">Exams for Approval</h1>
  <ul class="list-group">
    <% if @exams_to_approve.any? %>
    <% @exams_to_approve.each do |exam| %>
      <li class="list-group-item d-flex justify-content-between align-items-center">
        <span><%= exam.subject %></span>
        <%= link_to 'Approve', approve_exam_path(exam), method: :post, class: 'btn btn-success btn-sm' %>
      </li>
      <% end %>
      <% else %>
        <h3> No Pending Exams for Approval </h3>
        <% end %>
  </ul>
</div>

app/views/admin/index.html.erb
<body>
  <nav class="navbar navbar-default">
    <div class="container">
      <div class="navbar-header">
        <a class="navbar-brand" href="#">Admin Portal</a>
      </div>
      <ul class="nav navbar-nav">
        <% if current_user %>
        <li><%= link_to "Hi, #{current_user.email}", edit_user_registration_path %></li>
        <% end %>
        <li><%= link_to 'Sign Out', destroy_user_session_path, method: :delete %></li>
       
        
      </ul>
    </div>
  </nav>

  <div class="container">
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>


    <a class="btn btn-primary invite-button" href="<%= send_user_invitation_path(role:'teacher') %>">Invite Teacher</a>
     <a class="btn btn-primary invite-button" href="<%= send_user_invitation_path(role:'student') %>">  Invite Student</a>
     <a class="btn btn-primary invite-button" href="<%= admin_view_admin_index_path %>"> All Exams </a>
     <a class="btn btn-primary invite-button" href="<%= review_scores_admin_index_path %>"> Review Exam Scores </a>
    <%= yield %>
  </div>
</body>
</html>

app/views/admin/review_scores.html.erb
<h1 class='text-center bg-primary'>Review Exam Scores</h1>

<% if @results.any? %>
  <table class="table table-striped table-bordered">
    <thead>
      <tr>
        <th>Student</th>
        <th>Exam</th>
        <th>Score</th>
      </tr>
    </thead>
    <tbody>
      <% @results.each do |result| %>
        <tr>
          <td><%= result.user.full_name %></td>
          <td><%= result.exam.subject %></td>
          <td><%= result.total_score %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <p>No exam scores available.</p>
<% end %>