config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: {
    invitations: 'devise/invitations',
    registrations: 'users/registrations'
  }


  # --------------------------------- STUDENT ----------------------------------
  get 'student_view', to: 'student#student_view'
  get 'student_view_exam_questions', to: 'student#student_view_exam_questions'
  get 'student_exams', to: 'student#student_exams'
  post 'student/submit_student_exam/:id', to: 'student#submit_student_exam', as: 'submit_student_exam'

  #----------------------------------- EXAMS Questions----------------------------------------
  resources :exams do
    resources :questions
  end

  resources :questions, only: %i[edit update]

  resources :questions do
    resources :answers, only: %i[new create show]
  end

  #------------------------------- Teacher ---------------------------------------
  resources :teachers, only: [:index] do
    collection do
      get 'review_scores', to: 'teacher#review_scores', as: :review_scores
      get 'review_exam', to: 'teacher#review_exam', as: :review_exam
    end
    member do
      get 'approval_request/:id', to: 'teacher#approval_request', as: :approval_request
    end
  end

  #--------------------------------- Admin ----------------------------------------
  namespace :admin do
    resources :invitations, only: %i[new create], path: '' do
      collection do
        get :new_invitation
        post :create_invitation
      end
    end
  end

  resources :admin, only: [] do
    collection do
      get 'admin_view', to: 'admin#admin_view'
      get 'review_scores', to: 'admin#review_scores'
      get 'admin_question/:id', to: 'admin#admin_question', as: :admin_question
      post 'approve/:id', to: 'admin#approve', as: :approve_exam
      put 'cancel/:id', to: 'admin#cancel', as: :admin_cancel_exam
    end
  end

  #----------------------------------- USER ---------------------------------------
  devise_scope :user do
    root 'devise/sessions#new'
    get 'devise/invitations/new', to: 'devise/invitations#new', as: :send_user_invitation
    get 'users/sign_out', to: 'devise/sessions#destroy'
  end

  #-------------------------------------------------------------------------------------
  resources :results


  get '/admin', to: 'admin#index', as: :admin_index_path
  get '/teacher', to: 'teacher#index', as: :teacher_index_path
  get '/student', to: 'student#index', as: :student_index_path
end

app/models/exam.rb
class Exam < ApplicationRecord
  enum status: { cancel:0 , approve:1 , sent:2 , submitted:3}

  belongs_to :teacher, class_name: 'User', foreign_key: 'teacher_id'
  belongs_to :user
  has_many :questions, dependent: :destroy
  validate :teacher_can_have_one_pending_exam, on: :create
  attribute :approved, default: false
  attribute :request_sent, :boolean, default: true
  has_many :results, dependent: :destroy
  has_many :users, through: :results
  validates :subject, presence: true

   def teacher_can_have_one_pending_exam
    if self.status == 'pending' && self.teacher.pending_exam.present?
      errors.add(:base, 'You already have a pending exam for approval.')
    end
  end
   scope :to_approve, -> { where(approved: false, status: 2) }
end

app/controllers/exams_controller.rb
# frozen_string_literal: true

# Exams Controller
class ExamsController < ApplicationController
  before_action :set_exam, only: %i[show edit update destroy]

  def index
    @exams = policy_scope(Exam)
  end

  def new
    @exam = Exam.new
    authorize @exam
  end

  def create
    exam_inputs = exam_params
    exam_inputs[:teacher_id] = current_user.id
    @exam = current_user.exams.build(exam_inputs)
    authorize @exam

    respond_to do |format|
      if @exam.save
        format.html { redirect_to exam_url(@exam), notice: 'Exam was successfully created.' }
        format.json { render :show, status: :created, location: @exam }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @exam.errors, status: :unprocessable_entity }
      end
    end
  end

  # when adding question --- makes ques object
  def show
    @question = @exam.questions.build
  end

  def edit; end

  def update
    respond_to do |format|
      if @exam.update(exam_params)
        format.html { redirect_to exam_url(@exam), notice: 'Exam was successfully updated.' }
        format.json { render :show, status: :ok, location: @exam }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @exam.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @exam.destroy
    redirect_to exams_url, notice: 'Exam was successfully destroyed.'
  end

  #----------------------------------------------------------------------------

  private

  def set_exam
    @exam = if current_user.admin?
              Exam.find(params[:id])
            else
              current_user.exams.find(params[:id])
            end
    authorize @exam
  end

  def exam_params
    params.require(:exam).permit(:subject, :start_time, :end_time, :status, :teacher_id)
  end
end

app/helpers/exam_helper.rb
# frozen_string_literal: true

module ExamHelper
end

app/views/exams/_form.html.erb
<%= form_with(model: exam, local: true) do |form| %>
<% if exam.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(exam.errors.count, "error") %> prohibited this Exam from being saved:</h2>

      <ul>
      <% exam.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :subject %>
    <%= form.text_field :subject, class: 'form-control' %>
    <% if @exam.errors[:subject].any? %>
      <div class="error">
        <%= @exam.errors[:subject].join(', ') %>
      </div>
    <% end %>
  </div>


 <div class="form-group">
  <%= form.label :start_time %>
  <%= form.datetime_field :start_time %>
  </div>

   <div class="form-group">
  <%= form.label :end_time %>
  <%= form.datetime_field :end_time %>
    </div>
  
  <div class="actions ">
    <%= form.submit class:'btn btn-primary' , style: 'margin-top: 20px;' %>
  </div>

<% end %>

app/views/exams/_mcq_question_form.html.erb
<div id="mcqs_question_form" style="display: none;">
  <div class="form-group">
    <%= f.label :content, 'MCQ Question Content' %>
    <%= f.text_area :content_mcqs, class: 'form-control' %>
  </div>
 
  <!-- Separate fields for each option -->
  <div class="form-group">
    <%= f.label :choices_0, 'Option A' %>
    <%= f.text_field :choices_0, class: 'form-control' %>
  </div>
  
  <div class="form-group">
    <%= f.label :choices_1, 'Option B' %>
    <%= f.text_field :choices_1, class: 'form-control' %>
  </div>
  
  <div class="form-group">
    <%= f.label :choices_2, 'Option C' %>
    <%= f.text_field :choices_2, class: 'form-control' %>
  </div>
  
  <div class="form-group">
    <%= f.label :choices_3, 'Option D' %>
    <%= f.text_field :choices_3, class: 'form-control' %>
  </div>

  <!-- Correct Option for MCQs -->
  <div class="form-group">
    <%= f.label :correct_option, 'Correct Option (e.g., A, B, C, D)' %>
    <%= f.text_field :correct_option_mcqs, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :score, 'Marks ' %>
    <%= f.text_field :score_mcqs, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.submit class: 'btn btn-primary' %>
  </div>
</div>

app/views/exams/_text_question_form.html.erb
<div id="text_question_form" style="display: none;">
  <div class="form-group">
    <%= f.label :content, 'Text Question Content' %>
    <%= f.text_area :content_text, class: 'form-control' %>
  </div>
    <div class="form-group">
    <%= f.label :correct_option, 'Correct Option ' %>
    <%= f.text_field :correct_option_text, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :score, 'Text Question Score' %>
    <%= f.text_area :score_text, class: 'form-control' %>
  </div>


  <div class="form-group">
   <%= f.submit class: 'btn btn-primary' %>
  </div>
</div>

app/views/exams/edit.html.erb
<div class="card">
  <div class="card-body">
     <div class="row justify-content-center  align-items-center bg-primary">
        <div class ="col-md-9">
        <h2 class='header text-center'>Editing Exam</h2>
        </div>
        
      </div>

<%= render 'form', exam: @exam %>
 <%= button_to 'Destroy', @exam, method: :delete, class: "btn btn-danger", data: { confirm: 'Are you sure?' } %>

<%= link_to 'Back', exams_path , class:'btn btn-success',style:'margin-top:20px;' %>
</div>

app/views/exams/index.html.erb
<div class="card">
  <div class="card-body">
     <div class="row justify-content-center  align-items-center bg-primary">
        <div class ="col-md-9">
        <h2>Exams</h2>
        </div>
        <div class="col-md-3 text-right ">
           <h2> <%= link_to 'New Exam', new_exam_path, class: 'btn btn-success' %></h2>
        </div>
      </div>
  
 
     <% @exams.each do |exam| %>
       <%= link_to exam do %>
        <div class="card project-card">
          <div class="card-body">
          
            <h4 class="card-title"><%= exam.subject %></h4>
           <% if current_user.request_sent? %>
               <% if exam.status !='approve' && exam.status =='sent' %>
               <button> Pending Request </button>
               <%end%>
                <% if exam.status=='approve' %>
                <button>Approved </button>
                <%end%>

               <% if exam.status !='approve' && exam.status !='sent' %>
               <%= link_to 'Request for Approval',approval_request_teacher_path(exam),class: 'btn btn-success' %>
               <% end %>
          
             <% else %>
               <% if exam.status !='approve' && exam.status =='sent' %>
               <button> Pending Request </button>
               <%end%>
                <% if exam.status=='approve' %>
                <button>Approved </button>
                <%end%>

                <% end %>


          </div>
          <hr>
        </div>
        <% end %>
     <% end %>

  </div>
 <h2> <%= link_to 'Back', teacher_index_path_path, class: 'btn btn-success' %></h2>
</div>

app/views/exams/new.html.erb
<div class="card">
  <div class="card-body">
    <div class="row justify-content-center align-items-center bg-primary">
      <div class="col-md-9">
        <h2 class='header text-center'>Add New Exam</h2>
      </div>
    </div>

    <%= render 'form', exam: @exam %>

    <%= link_to 'Back', teacher_index_path_path, class: 'btn btn-success', style: 'margin-top: 20px;' %>
  </div>
</div>

app/views/exams/show.html.erb
<div class="card">
  <div class="card-body">
    <div class="row justify-content-center align-items-center bg-primary">
      <div class="col-md-9">
        <h2><%= @exam.subject %></h2>
      </div>
      <div class="col-md-3 text-right">
        <h2>
          <%= button_to 'Destroy', @exam, method: :delete, class: "btn btn-danger", data: { confirm: 'Are you sure?' } %>
        </h2>
      </div>
    </div>

    <h4>Add Question</h4>

    <%= form_with(model: [@question.exam, @question], html: { class: 'form-group' }) do |f| %>
      <% if @question.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@question.errors.count, "error") %> prohibited this question from being saved:</h2>
          <ul>
            <% @question.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <div class="form-group">
        <%= f.label :question_type %>
        <%= f.select :question_type, Question.question_types.keys.map { |type| [type.humanize, type] }, {}, { id: 'question_type', class: 'form-control' } %>
      </div>

      <!-- Text Question Form Partial -->
      <%= render 'text_question_form', f: f %>

      <!-- MCQs Question Form Partial -->
      <%= render 'mcq_question_form', f: f %>
    <% end%>
  </div>

  <div class="card-footer bg-light">
    <h1 class='question_head text-center'>Questions</h1>

    <% @exam.questions.each do |question| %>
      <% if question.persisted? %>
        <div class='qs-item'>
          <p><strong>Question </strong><%= question.content %></p>
          <% if question.question_type == 'mcq' %>
            <p><strong>Options </strong><%= question.choices %></p>
          <% end %>
          <p><strong>Correct Option: </strong><%= question.correct_option %></p>
          <p><strong>Score: </strong><%= question.score %></p>
        </div>


        <%= button_to 'Destroy', [question.exam, question], method: :delete, class: 'btn btn-danger', style: 'margin-left:20px', data: { confirm: 'Are you sure?' } %>
      <% end %>
      <hr>
    <% end %>
  </div>
  <%= link_to 'Back', exams_path, class: 'btn btn-success' %>
</div>

<script>
  $(document).ready(function () {
    // Use event delegation to handle change event
    $(document).on('change', '#question_type', function () {
      if ($(this).val() === 'text') {
        $('#text_question_form').show();
        $('#mcqs_question_form').hide();
      } else if ($(this).val() === 'mcq') {
        $('#text_question_form').hide();
        $('#mcqs_question_form').show();
      } else {
        console.log("Kuch ni bhae chlrha")
        $('#text_question_form').hide();
        $('#mcqs_question_form').hide();
      }
    });
  });
</script>